version: "3"
services:
  mariadb:
    image: mariadb:10.4
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: test
    restart: always
  webserver:
    image: phpstorm/php-73-apache-xdebug-27
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal